# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-10 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='favorite',
        ),
    ]
