# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-10 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190710_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='favorite',
            new_name='featured',
        ),
    ]
