# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-16 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_auto_20190710_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(choices=[('not seen', 'Not Seen'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('hats', 'Hats'), ('accesories', 'Accesories')], default='not seen', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('not seen', 'Not Seen'), ('nike', 'Nike'), ('adidas', 'Adidas'), ('converse', 'Converse'), ('levis', 'Levis')], default='not seen', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to=products.models.upload_image_path),
        ),
    ]
