# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-18 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190716_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(choices=[('not seen', 'Not Seen'), ('Outerwear', 'Outerwear'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('accesories', 'Accesories')], default='not seen', max_length=100),
        ),
    ]
