# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190718_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(choices=[('other', 'Other'), ('Outerwear', 'Outerwear'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('accesories', 'Accesories')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('other', 'Other'), ('nike', 'Nike'), ('adidas', 'Adidas'), ('converse', 'Converse'), ('levis', 'Levis')], default='other', max_length=100),
        ),
    ]
