# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190718_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
