# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190718_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(choices=[('other', 'Other'), ('Outerwear', 'Outerwear'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('footwear', 'Footwear'), ('accesories', 'Accesories')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/default.png', upload_to=products.models.upload_image_path),
        ),
    ]
