# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-21 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190719_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
