# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
