# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-21 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190720_1804'),
        ('products', '0021_auto_20190721_0216'),
    ]

    operations = [
    ]
