# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-07 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Slug',
            new_name='slug',
        ),
    ]
